# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
  rev: 'v0.0.261'
  hooks:
      - id: ruff
